steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
serviceAccount: "cicd-sa@storied-core-424404-t8.iam.gserviceaccount.com"
options:
  logging : CLOUD_LOGGING_ONLY
timeout: 1600s
